version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: motorbikedb
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - client-service
      - motorbike-service
      - reservation-service
      - payment-service
    environment:
      - SPRING_PROFILES_ACTIVE=default

  client-service:
    build: ./client-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/clientdb

  motorbike-service:
    build: ./motorbike-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/motorbikedb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

  reservation-service:
    build: ./reservation-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/reservationdb?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/paymentdb

volumes:
  mongo_data:
  mysql_data: 