server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 247196131266-8o3qkvdqtp8gfqtqp9tlbuut4b37jetj.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: motorbike-service
          uri: http://motorbike-service:8081
          predicates:
            - Path=/motorbikes/**
        - id: client-service
          uri: http://client-service:8082
          predicates:
            - Path=/clients/**
        - id: reservation-service
          uri: http://reservation-service:8083
          predicates:
            - Path=/reservations/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/payments/**
