name: CI/CD Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'maven'
          distribution: 'temurin'

      - name: Run unit tests for api-gateway
        run: mvn package -B
        working-directory: ./api-gateway

      - name: Run unit tests for client-service
        run: mvn package -B
        working-directory: ./client-service

      - name: Run unit tests for motorbike-service
        run: mvn package -B
        working-directory: ./motorbike-service

      - name: Run unit tests for reservation-service
        run: mvn package -B
        working-directory: ./reservation-service

      - name: Run unit tests for payment-service
        run: mvn package -B
        working-directory: ./payment-service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build api-gateway image
        run: docker build -t api-gateway ./api-gateway

      - name: Build client-service image
        run: docker build -t client-service ./client-service

      - name: Build motorbike-service image
        run: docker build -t motorbike-service ./motorbike-service

      - name: Build reservation-service image
        run: docker build -t reservation-service ./reservation-service

      - name: Build payment-service image
        run: docker build -t payment-service ./payment-service

      - name: Build docker-compose (optional)
        run: docker compose build
