name: CI/CD Build, Test, and Dockerize Microservices

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build and test all microservices in parallel using a matrix
  build-and-test:
    name: Build & Test Microservices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - client-service
          - motorbike-service
          - reservation-service
          - payment-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'maven'
          distribution: 'temurin'

      - name: Build and test ${{ matrix.service }}
        run: mvn package -B
        working-directory: ./${{ matrix.service }}

  # Build Docker images for all services after successful build & test
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build api-gateway image
        run: docker build -t api-gateway ./api-gateway

      - name: Build client-service image
        run: docker build -t client-service ./client-service

      - name: Build motorbike-service image
        run: docker build -t motorbike-service ./motorbike-service

      - name: Build reservation-service image
        run: docker build -t reservation-service ./reservation-service

      - name: Build payment-service image
        run: docker build -t payment-service ./payment-service

      # Optionally, build all images with docker-compose
      - name: Build all images with docker-compose (optional)
        run: docker compose build
        continue-on-error: true

  # Optionally, add a summary job for test results or notifications
  # You can also add jobs for pushing images to a registry, deploying, etc.
