name: CI/CD Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - client-service
          - motorbike-service
          - reservation-service
          - payment-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          cache: 'maven'
          distribution: 'temurin'

      - name: Build and test ${{ matrix.service }}
        run: mvn package -B
        working-directory: ./${{ matrix.service }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build api-gateway image
        run: docker build -t api-gateway ./api-gateway

      - name: Build client-service image
        run: docker build -t client-service ./client-service

      - name: Build motorbike-service image
        run: docker build -t motorbike-service ./motorbike-service

      - name: Build reservation-service image
        run: docker build -t reservation-service ./reservation-service

      - name: Build payment-service image
        run: docker build -t payment-service ./payment-service

      - name: Build docker-compose (optional)
        run: docker compose build
